<?php
/**
 * @file
 * Code for the design feature.
 */

include_once 'design.features.inc';

/**
 * Implements hook_node_presave().
 * 
 * Adds logic to include view field if there are related nodes.
 * Also dynamically adds appropriate contextual filter arguments based
 * on selected tids.
 */

function design_node_presave($node) {

  if (($node->type == "design_phase_task") && isset($node->field_related_job_aids_view)) {

    $job_aids_output = "";

    // If the node has related technical job aid terms, add Arguments.

    if (isset($node->field_related_job_aids['und'][0])) {

      foreach ($node->field_related_job_aids['und'] as $key => $term) {
        if ($key == 0) {
          $job_aids_output .= $term['tid'];
        } else {
          $job_aids_output .= "+" . $term['tid'];
        }
      }

      $node->field_related_job_aids_view['und'][0]['vargs'] = $job_aids_output;

      $node->field_related_job_aids_view['und'][0]['vname'] = "technical_job_aids|block_1";
    } else {
      // Otherwise, don't even add a view
      $node->field_related_job_aids_view = "";
    }

    $online_teaching_docs_output = "";

    // If the node has related online teaching terms, add Arguments.

    if (isset($node->field_related_teaching_online['und'][0])) {

      foreach ($node->field_related_teaching_online['und'] as $key => $term) {
        if ($key == 0) {
          $online_teaching_docs_output .= $term['tid'];
        } else {
          $online_teaching_docs_output .= "+" . $term['tid'];
        }
      }

      $node->field_related_teaching_online_vi['und'][0]['vargs'] = $online_teaching_docs_output;

      $node->field_related_teaching_online_vi['und'][0]['vname'] = "online_teaching_guides|block_1";

    } else {
      // Otherwise, don't even add a view
      $node->field_related_teaching_online_vi = "";
    }

  }
}

/**
 * Implements hook_form_alter().
 * 
 * Hides views field on the form
 */

function design_form_alter(&$form, &$form_state, $form_id) {

  if ((isset($form['type']['#value'])) && $form['type']['#value'] != "design_phase_task") {
    return;
  }

  $form['field_related_job_aids_view']['#attributes']['class'][] = 'hidden-form-element';
  $form['field_related_teaching_online_vi']['#attributes']['class'][] = 'hidden-form-element';

}

/**
 * Implements hook_preprocess_node().
 * 
 * Adds JS to design_phase_compoment pages.
 */

function design_preprocess_node(&$variables) {
  if ($variables['type'] == 'design_phase_component') {
    drupal_add_js(drupal_get_path('module', 'design') . "/design_tasks.js", "file");
  }
}

/** Implements hook_node_view_alter().
 *
 * Changes design phase task layout depending on node fields
 */

function design_node_view_alter(&$build) {
    if ($build['#bundle'] != 'design_phase_task') {
      return;
    }

    // It both view fields are set, change text width and float.
    if (isset($build['field_related_job_aids_view']) || isset($build['field_related_teaching_online_vi'])) {
      $build['field_design_phase_task_overview'][0]['#prefix'] = "<div class='push-left'>";
      $build['field_design_phase_task_overview'][0]['#suffix'] = "</div>";
    }

    // If just the teaching view field is set, add class to change the clear attribute.
    if (isset($build['field_related_teaching_online_vi']) && !isset($build['field_related_job_aids_view'])) {
      $build['field_related_teaching_online_vi']['#prefix'] = "<div class='view-field-clear-none'>";
      $build['field_related_teaching_online_vi']['#suffix'] = "</div>";
    }
}

