<?php
/**
 * @file
 * Code for the design_model_graphics module
 */

/**
 * Implements hook_init().
 *
 * Adds raphael library and custom JS file.
 */


function design_model_graphic_init() {

  drupal_add_library('raphael', 'raphael', TRUE);

  if ($_GET['q'] == 'plan' || 'instructional-design-process') {
    drupal_add_js(drupal_get_path('module', 'design_model_graphic') . '/model_graphic_small.js');
  }
  
  if ($_GET['q'] == 'instructional-design-process') {
    drupal_add_js(drupal_get_path('module', 'design_model_graphic') . '/model_graphic.js');
  }

}

